### PR TITLE
Fix getMethod

### PR DESCRIPTION
**Pull request by UltCombo**
Reference: https://people.mozilla.org/~jorendorff/es6-draft.html#sec-getmethod

### CODE REVIEW

**Comment by domenic** [comment]
Tests showing the difference?

**Comment by UltCombo** [comment]
Added test.

**Comment by UltCombo** [comment]
I can squash the commits if you'd like and if it is okay for merging.

**Comment by domenic** [comment]
Can you test Get vs. GetV?

**Comment by UltCombo** [comment]
Yes, but I just realized something odd. With this change, [this test](https://github.com/domenic/especially/blob/83b507b1dd6f271daedaa62166b5dc83a9eb499f/test/abstract-operations.js#L1135) should not be passing anymore. Oh, that's because [this assertion](https://github.com/UltCombo/especially/blob/302201530fb66c49c1e9803f2094114e2375b122/abstract-operations.js#L454) must be removed as well.

**Comment by UltCombo** [comment]
PTAL.

**Comment by UltCombo** [comment]
The only difference I see is that Get would throw an error for non-objects while GetV boxes them.
As GetMethod does an IsPropertyKey assertion before calling GetV, there's no observable difference between GetV and [[Get]] in this case, as far as I can see.

**Comment by UltCombo** [comment]
Just to be sure, when you asked for Get vs. GetV, you actually mean [[Get]] vs. GetV? There's no observable change as [mentioned above](https://github.com/domenic/especially/pull/6#issuecomment-122632430).
[Get](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-get-o-p) was never part of the code.

**Comment by UltCombo** [comment]
Does this need anything else to be merged? @domenic

**Comment by domenic** [comment]
Merged as 523059eea61a9ad16cace92a14b35429a0aeb5d9; 2.0.1 coming shortly.

**Comment by UltCombo** [comment]
Thanks!

**Pull request closed without merging**
